### ISSUE TITLE
model file error,  example in documentation includes "tree",  but this triggers error

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#21]
I tried running the documentation example model file
this line "tree": (Troglodytes,Verus);
triggered this error
exp_handler - ERROR: Expecting value: line 4 column 13 (char 36)
Traceback (most recent call last):
  File "/home/jodyhey/anaconda3/envs/py-popgen/bin/vcf_filter.py", line 847, in <module>
    run()
  File "/home/jodyhey/anaconda3/envs/py-popgen/bin/vcf_filter.py", line 459, in run
    models_in_file = read_model_file(vcf_args.model_file)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/model.py", line 391, in read_model_file
    models_dict = json.load(model_file)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/jodyhey/anaconda3/envs/py-popgen/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 13 (char 36)

Wen I delete that line it runs.

**Comment by aewebb80** [comment]
Updated the documentation in (978e0757ee11fe3bcf175b5eed05d1b34e2c0a2d) the error was due to a semantics error:
`"tree": (Troglodytes,Verus);` should have been `"tree": "(Troglodytes,Verus);",`
