### ISSUE TITLE
informative_loci_filter  not running on .vcf.gz

### ISSUE THREAD

**Issue by jodyhey** [jaredgk/PPP#31]
this command line:
informative_loci_filter.py --vcf alyrata.7Pop.Filtered.vcf.gz --bed  alyrata_3kb_intersects.bed --remove-indels --minsites 4 --keep-full-line --out alyrata_3kb_informativex.bed &> bed_informativex.out &

gave this error:
exp_handler - ERROR: start out of range (-1)
Traceback (most recent call last):
  File "/home/jodyhey/miniconda3/envs/py-popgen/bin/informative_loci_filter.py", line 260, in <module>
    filter_bed_regions(sys.argv[1:])
  File "/home/jodyhey/miniconda3/envs/py-popgen/bin/informative_loci_filter.py", line 231, in filter_bed_regions
    rec_list = vcf_reader.getRecordList(region)
  File "/home/jodyhey/miniconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/vcf_reader_func.py", line 405, in getRecordList
    return getRecordList(self.reader, region, chrom, start, end, self.chr_in_chrom)
  File "/home/jodyhey/miniconda3/envs/py-popgen/lib/python3.7/site-packages/pgpipe/vcf_reader_func.py", line 516, in getRecordList
    var_sites = vcf_reader.fetch(c, region.start, region.end)
  File "pysam/libcbcf.pyx", line 4372, in pysam.libcbcf.VariantFile.fetch
  File "pysam/libchtslib.pyx", line 691, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-1)

**Comment by jaredgk** [comment]
I've changed all of my scripts to default to the normal BED file convention of having regions be in zero-based, half-open coordinates (like what Andrew's scripts are outputting) so this should be fixed. Also adding an exception if a region start (or end) coordinate is less than 0.
