### ISSUE TITLE
vcf to gphocs

### ISSUE THREAD

**Issue by glaudelrio** [jaredgk/PPP#33]
Hi, I keep getting this error when using vcf_to_gphocs.py:

[W::bcf_hdr_check_sanity] GL should be declared as Number=G
exp_handler - ERROR: "sequence 'contig1' not present"
Traceback (most recent call last):
  File "/scratch/gdleri1/PPP/pgpipe/vcf_to_gphocs.py", line 263, in <module>
    run(**args)
  File "/scratch/gdleri1/PPP/pgpipe/vcf_to_gphocs.py", line 257, in run
    nloci=gphocs_args.nloci)
  File "/scratch/gdleri1/PPP/pgpipe/vcf_to_gphocs.py", line 185, in make_gphocs_sequence_file
    regionstr,s = next(a)# should raise StopIteration if generator is exhausted
  File "/home/gdleri1/.local/lib/python3.6/site-packages/py_popgen-0.1.10-py3.6.egg/pgpipe/vcf_bed_to_seq.py", line 426, in get_model_sequences
    seqstr = fasta_access.fetch(region=regionstr)
  File "pysam/libcfaidx.pyx", line 303, in pysam.libcfaidx.FastaFile.fetch
KeyError: "sequence 'contig1' not present"

However, my reference fasta file, vcf file, and bed file, all have chromosome names as "contig#" 
What would be the issue?
Thank you so much!

**Comment by jodyhey** [comment]
I just tried this on some test files for which I changed the name of a fasta record, bed file chromosome column, and corresponding positions in vcf file,  to 'contig1'  

It gives a couple warnings,  but otherwise ran fine.   Can you shared paired down files that still cause the problem?
