### ISSUE TITLE
vcf_to_gphocs failed

### ISSUE THREAD

**Issue by willright28** [jaredgk/PPP#37]
Hi all,
Tried to use vcf_to_gphocs.py but get an error message:

2021-11-22 18:56:31,183 - exp_handler - ERROR: Expecting value: line 22 column 17 (char 534)
Traceback (most recent call last):
  File "/home/sparrow/.conda/envs/py-popgen/bin/vcf_to_gphocs.py", line 263, in <module>
    run(**args)
  File "/home/sparrow/.conda/envs/py-popgen/bin/vcf_to_gphocs.py", line 253, in run
    popmodels = read_model_file(gphocs_args.model_file)
  File "/home/sparrow/.conda/envs/py-popgen/lib/python3.7/site-packages/pgpipe/model.py", line 426, in read_model_file
    models_dict = json.load(model_file)
  File "/home/sparrow/.conda/envs/py-popgen/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/sparrow/.conda/envs/py-popgen/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/sparrow/.conda/envs/py-popgen/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/sparrow/.conda/envs/py-popgen/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 22 column 17 (char 534)

Anyone has clues? Thanks in advance!

**Comment by jodyhey** [comment]
can you provide any info about the command line and data you were using?
