### ISSUE TITLE
vcf_to_ima.py error

### ISSUE THREAD

**Issue by xwang111** [jaredgk/PPP#40]
Hello, I got the following error when converting data formats.
command line:
vcf_to_ima.py --vcfs chr01_4gt/chr01_4gt_Chr01-797055-798759.vcf chr01_4gt/chr01_4gt_Chr01-819732-821385.vcf chr01_4gt/chr01_4gt_Chr01-911114-911172.vcf chr01_4gt/chr01_4gt_Chr01-953191-971522.vcf chr01_4gt/chr01_4gt_Chr01-1106335-1157414.vcf --out chr01_ima3_5 --model-file out.model 

Traceback (most recent call last):
  File "/home/miniconda3/envs/py-popgen/bin/vcf_to_ima.py", line 697, in <module>
    vcf_to_ima(**parseArguments())
  File "/home/miniconda3/envs/py-popgen/bin/vcf_to_ima.py", line 675, in vcf_to_ima
    raise Exception("Individual %d from pop %s at loci %d, site %d is missing data" % (indiv_idx,p,record_count,i))
Exception: Individual 4 from pop T.ciliata_var_ciliata at loci 1, site 0 is missing data

What could I do with my data,  please?

**Comment by arunsethuraman** [comment]
Can you please share a sample input file (VCF) and model file (out.model)? This looks like some formatting error in either of those.

**Comment by xwang111** [comment]
Dear Sethuraman,


This is the&nbsp;input file (VCF) and model file (out.model),&nbsp;please see if there is anything wrong with it.&nbsp;


Thank you！
Xi Wang


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jaredgk/PPP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 晚上11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jaredgk/PPP] vcf_to_ima.py error (Issue #40)





 
Can you please share a sample input file (VCF) and model file (out.model)? This looks like some formatting error in either of those.

**Comment by xwang111** [comment]
hi Sethuraman,

I've solved the problem. I replaced the missing sites with reference bases and it worked. 
But there was another error as below when I  performed IMa3 analysis:

command line:
ima3_wrapper.py -i test2 -o test2.out -q5 -m0.5 -t1 -b10000 -L10000 --ima-path ~/miniconda3/envs/py-popgen/bin/IMa3

Traceback (most recent call last):
  File "/home/lilingling/miniconda3/envs/py-popgen/bin/ima3_wrapper.py", line 178, in <module>
    run(sys.argv[1:])
  File "/home/lilingling/miniconda3/envs/py-popgen/bin/ima3_wrapper.py", line 172, in run
    call_ima3(misc_args,ima_arglist)
  File "/home/lilingling/miniconda3/envs/py-popgen/bin/ima3_wrapper.py", line 147, in call_ima3
    raise Exception("Error with IMa call:%d\n%s"%(ima_call.returncode,ima_stderr))
Exception: Error with IMa call:36
IMa3: data not compatible with infinite sites model - locus #: 0, name: Chr01:797055:798603,  sequence#: 47

But I have already done the four-gamete test (using vcf_four_gamete.py), and I'm confused as why it still reports this error.
