### ISSUE TITLE
Cannot update model file

### ISSUE THREAD

**Issue by Neato-Nick** [jaredgk/PPP#46]
Hi, I'm trying to set up models and model files, but I cannot modify models. I've tried using files and example code

Following [Example #3](https://ppp.readthedocs.io/en/latest/PPP_pages/Functions/model_creator.html#example-3-update-model-in-model-file), I cannot create or remove populations from a model :
```
# create model that will be updated
model_creator.py --model 2Pops --out Pops.model \
--model-pop 2Pops Troglodytes \
--pop-ind-file Troglodytes Troglodytes.txt
# update model in model file
model_creator.py --model-file Pops.model --update-model 2Pop \
--model-rm-pop 2Pop Troglodytes \
--model-pop 2Pop Paniscus \
--pop-ind-file Paniscus Paniscus.txt
# check for differences
diff Pops.model out.model
```

I also cannot add new models to a model file, there isn't an example for exactly this case but from reading the documentation I thought it should be possible
```
model_creator.py --model-file Pops.model --model Paniscus_only \
--model-pop Paniscus_only Paniscus \
--pop-ind-file Paniscus Paniscus.txt
#> output
initLogger - WARNING: PPP, version 0.1.13
run - WARNING: No tree assigned to model (Paniscus_only)
exp_handler - ERROR: No individuals found in Paniscus_only.
Traceback (most recent call last):
  File "/home/bpp/carleson/.local/bin/model_creator.py", line 759, in <module>
    run(**model_creator_parser())
  File "/home/bpp/carleson/.local/bin/model_creator.py", line 749, in run
    model_file[model] = model_data
  File "/home/bpp/carleson/.local/lib/python3.7/site-packages/pgpipe/model.py", line 31, in __setitem__
    self.update_inds(model = arg[1])
  File "/home/bpp/carleson/.local/lib/python3.7/site-packages/pgpipe/model.py", line 71, in update_inds
    raise IOError('No individuals found in %s.' % model.name)
OSError: No individuals found in Paniscus_only.
```

Hopefully I'm just overlooking and missing a simple parameter here. My temporary workaround is to create a new model file for every model, but my directory is getting clogged with model files. Thank you for any guidance.

**Comment by ezcn** [comment]
Hi I am having the exact same issue. Any update? 
Thanks!

**Comment by Neato-Nick** [comment]
Sorry I can't help you! I was not able to solve the issue, and I stopped
using the software.
